import { getAllPosts, getPostByFile } from '../../../lib/blog/get-posts';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import ReactMarkdown from 'react-markdown';

export const dynamic = 'force-dynamic';

export function generateStaticParams() {
  return getAllPosts().map((p) => ({ slug: p.file }));
}

export default async function BlogPostPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = getPostByFile(decodeURIComponent(slug));
  if (!post) notFound();

  return (
    <main className="max-w-3xl mx-auto px-6 py-12">
      <Link href="/blog" className="text-sm text-gray-400 hover:text-orange-600 mb-8 inline-block">
        &larr; Back to all drafts
      </Link>

      <header className="mb-10">
        <div className="flex items-center gap-3 mb-4">
          <span className="text-xs font-medium uppercase tracking-wider text-orange-600 bg-orange-50 px-2 py-0.5 rounded">
            {post.category.title}
          </span>
          <span className="text-sm text-gray-400">{post.publishedAt}</span>
          <span className="text-sm text-gray-400">{post.wordCount} words</span>
        </div>
        <h1 className="text-4xl font-bold tracking-tight leading-tight mb-4">{post.title}</h1>
        <p className="text-lg text-gray-500">{post.metaDescription}</p>
      </header>

      <article className="prose prose-lg prose-gray max-w-none prose-headings:font-semibold prose-headings:tracking-tight prose-h2:text-2xl prose-h2:mt-10 prose-h2:mb-4 prose-p:leading-relaxed prose-p:text-gray-700">
        <ReactMarkdown>{post.content}</ReactMarkdown>
      </article>

      <footer className="mt-16 pt-8 border-t border-gray-200 text-sm text-gray-400">
        <p>Draft generated by UltraPlan &middot; {post.author} &middot; File: {post.file}</p>
      </footer>
    </main>
  );
}
